"""

Revision ID: 3077cf5e69c8
Revises: 772e8eeb7ed4
Create Date: 2026-04-24 07:36:56.857063

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3077cf5e69c8"
down_revision: Union[str, Sequence[str], None] = "772e8eeb7ed4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.execute("CREATE TYPE userroleenum AS ENUM('WORKER', 'ADMIN', 'CLIENT')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=25), nullable=False),
        sa.Column("tg_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM(
                "WORKER", "ADMIN", "CLIENT", name="userroleenum", create_type=False
            ),
            server_default="CLIENT",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tg_id"),
    )
    op.drop_constraint(op.f("orders_worker_id_fkey"), "orders", type_="foreignkey")
    op.drop_constraint(op.f("orders_client_id_fkey"), "orders", type_="foreignkey")
    op.drop_table("clients")
    op.drop_table("workers")

    op.execute(
        "ALTER TABLE orders ADD CONSTRAINT orders_client_id_fkey FOREIGN KEY (client_id) REFERENCES users (id) ON DELETE CASCADE"
    )
    op.execute(
        "ALTER TABLE orders ADD CONSTRAINT orders_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES users (id) ON DELETE CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.create_foreign_key(
        op.f("orders_client_id_fkey"),
        "orders",
        "clients",
        ["client_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("orders_worker_id_fkey"),
        "orders",
        "workers",
        ["worker_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_table(
        "workers",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=25), autoincrement=False, nullable=False),
        sa.Column("tg_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("workers_pkey")),
        sa.UniqueConstraint(
            "tg_id",
            name=op.f("workers_tg_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "clients",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=25), autoincrement=False, nullable=False),
        sa.Column("tg_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("clients_pkey")),
        sa.UniqueConstraint(
            "tg_id",
            name=op.f("clients_tg_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table("users")
    # ### end Alembic commands ###
