"""Add username field to User

Revision ID: 3ca33ddb5bec
Revises: 3077cf5e69c8
Create Date: 2026-04-29 08:32:53.674751

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3ca33ddb5bec"
down_revision: Union[str, Sequence[str], None] = "3077cf5e69c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "username")
    # ### end Alembic commands ###
